### ISSUE TITLE
Allow users to be appended to the `pdns` unix group

### ISSUE THREAD

**Issue by poblahblahblah** [dnsimple/chef-pdns#81]
Hello,

We're currently looking at using PowerDNS for our internal DNS needs. When getting a wrapper cookbook created and tested I noticed that our monitoring agent, telegraf, did not have read access to the PowerDNS control socket, which it needs in order to grab metrics. My first thought was to add the `telegraf` user to the `pdns` unix group, but it looks like this cookbook strictly controls[0] the membership of the group, so all changes are added and removed in a single chef run.

What we ended up doing was setting the `setgid` directive to `telegraf`, which seems to work, although I think it would be cleaner if we were allowed to append members to the `pdns` group.

I can get a PR going for this change if you would like, but I wanted to discuss the idea or any alternatives before doing so.

Thank you!

0 - https://github.com/dnsimple/chef-pdns/blob/master/resources/pdns_authoritative_config.rb#L66

**Comment by onlyhavecans** [comment]
Hey there! I agree with your use case. Since it's such a trivial change to use `ammend true` and I don't see how it could be breaking I popped open a quick PR [here](https://github.com/dnsimple/chef-pdns/pull/82). If you agree that works let me know.

I'd like to have @martinisoft chime in on this so I put him on reviewers as well.

**Comment by martinisoft** [comment]
I'm ok with the change. I've just released 4.0 which was the bigger change set so I'll probably merge that change into 4.1.0 if you're ok with that @poblahblahblah

**Comment by poblahblahblah** [comment]
@martinisoft That sounds good to me - I appreciate the quick turnaround!
