### ISSUE TITLE
issue in running the test recipe

### ISSUE THREAD

**Issue by krishnaghatti** [dnsimple/chef-pdns#83]
Hi,
I was trying out the test recipe given and I get the below error.

`Chef::Exceptions::InvalidResourceSpecification
----------------------------------------------
The string `pdns_authoritative_service[]' is not valid for resource collection lookup. Correct syntax is `resource_type[resource_name]'

Cookbook Trace:
---------------
  /var/chef/runs/cc707120-4eb1-4025-b2f9-f71d9a2746f9/local-mode-cache/cache/cookbooks/powerdns/recipes/authoritative_setup2.rb:49:in `block in from_file'
  /var/chef/runs/cc707120-4eb1-4025-b2f9-f71d9a2746f9/local-mode-cache/cache/cookbooks/powerdns/recipes/authoritative_setup2.rb:39:in `from_file'

Relevant File Content:
----------------------
/var/chef/runs/cc707120-4eb1-4025-b2f9-f71d9a2746f9/local-mode-cache/cache/cookbooks/powerdns/recipes/authoritative_setup2.rb:

 42:    variables(
 43:      gpgsql_host: '127.0.0.1',
 44:      gpgsql_user: 'pdns',
 45:      gpgsql_port: 5432,
 46:      gpgsql_dbname: 'pdns',
 47:      gpgsql_password: 'mypassword'
 48:    )
 49>>   notifies :restart, 'pdns_authoritative_service[]'
 50:  end
 51:
 52:  file '/etc/powerdns/pdns.d/pdns.local.gmysql.conf' do
 53:    action :delete
 54:    only_if { File.exist? '/etc/powerdns/pdns.d/pdns.local.gmysql.conf' }
 55:  end
 56:
 57:  pdns_authoritative_service '' do
 58:    action [:enable, :start]`

Am I missing anything?

**Comment by martinisoft** [comment]
Hi @krishnaghatti 

Which version of Chef were you using? I think I'll need to further clarify the documentation a little more about this and maybe review default naming schemes.

What I would suggest for now is that you name your authoritative service something and set the 'instance_name' property to an empty string.

For example:

```ruby
pdns_authoritative_config '' do
  action :create
  launch ['gpgsql']
  variables(
    gpgsql_host: '127.0.0.1',
    gpgsql_user: 'pdns',
    gpgsql_port: 5432,
    gpgsql_dbname: 'pdns',
    gpgsql_password: 'wadus'
  )
  notifies :restart, 'pdns_authoritative_service[default]'
end

pdns_authoritative_service 'default' do
  instance_name ''
  action [:enable, :start]
end
```

**Comment by krishnaghatti** [comment]
Hi @martinisoft 
Thank you for a quick response. Yes the suggested steps did work.

**Comment by martinisoft** [comment]
Good to hear @krishnaghatti 

I'd still like to know which version of Chef you are using. The test recipe you are using works in our test suite which is running Chef 13.2 at the moment.

**Comment by krishnaghatti** [comment]
Hey @martinisoft 
missed to add that detail.
I am using 12.18 on AWS Opsworks.

**Comment by martinisoft** [comment]
Good to know. I will try to track down some chef client versioning nuances here. I wonder if the empty resource thing is a bugfix or something different in the newer releases of Chef.

**Comment by onlyhavecans** [comment]
Thanks for following up
