### ISSUE TITLE
Getting an error if I do not stop pdns service

### ISSUE THREAD

**Issue by maurice-bva** [dnsimple/chef-pdns#88]
This is the first time I use chef. So bear with me here.

[pdns.txt](https://github.com/dnsimple/chef-pdns/files/1434861/pdns.txt)

If I remove the part that stops the pdns process and do a 'kitchen converge' I end up with an error. The script tries running "pdns_authoritative_service" to enable and start the process. But It can't as a pdns process is already running. I have to stop the pdns process before "pdns_authoritative_service" runs without a hitch.  Not sure if I'm doing anything wrong, but I found it strange that is is not working out of the box so to speak

**Comment by martinisoft** [comment]
Hi @maurice-bva 

Can you tell me which Chef Version and platform you were getting this issue with? A backtrace would also be helpful as well.

**Comment by martinisoft** [comment]
Hi again @maurice-bva 

Since we haven't heard from you we'll be closing this issue. If you have feedback for us please feel free to re-open the issue and update us.
