### ISSUE TITLE
Configuration permissions issues

### ISSUE THREAD

**Issue by mengesb** [dnsimple/chef-pdns#89]
Seems that the configuration files may not be using the pdns user; and instead use `root`

In the case of recursor, using `rec_control` to reload the config results in:
```
Encountered error reloading zones, keeping original data: Unable to re-parse configuration file '/etc/pdns-recursor/recursor-__name__.conf'
```

This was resolved by the performing one of the following:
* Updating file permissions of the config to `0644`
* chown the configuration files to the pdns user (pdns-recursor in recursor's case)

https://github.com/dnsimple/chef-pdns/blob/master/resources/recursor_config.rb#L85
https://github.com/dnsimple/chef-pdns/blob/master/resources/authoritative_config.rb#L86

**Comment by onlyhavecans** [comment]
Great catch. I'll PR this right away

**Comment by onlyhavecans** [comment]
I opened #90 to resolve this

**Comment by mengesb** [comment]
@onlyhavecans you beat me to the punch! I was just about to push my PR to my fork!!!

**Comment by onlyhavecans** [comment]
🤣 If you have a preferred way to address this I am open to seeing your fork.
We aim to squash bugs as rapidly as possible.

**Comment by onlyhavecans** [comment]
@mengesb I have the patch out. Please let me know if you have any more issues!

**Comment by mengesb** [comment]
I'll test it very soon! Just finished my wrapper cookbook!
