### ISSUE TITLE
Fix Testing

### ISSUE THREAD

**Issue by mengesb** [dnsimple/chef-pdns#91]
In an effort to submit a PR to fix some things, I've noticed that the testing has gone out of whack.

One change that's simple I noticed was a record reply change:
```
diff --git i/test/integration/recursor-multi/default_spec.rb w/test/integration/recursor-multi/default_spec.rb
index ebc972e..0dc7ba6 100644
--- i/test/integration/recursor-multi/default_spec.rb
+++ w/test/integration/recursor-multi/default_spec.rb
@@ -39,9 +39,9 @@ describe command('dig -p 54 chaos txt version.bind @127.0.0.1 +short') do
 end

 describe command('dig -p 53 @127.0.0.1 dnsimple.com') do
-  its('stdout') { should match(Regexp.new(/208.93.64.253/)) }
+  its('stdout') { should match(Regexp.new(/104.245.210.170/)) }
 end

 describe command('dig -p 54 @127.0.0.1 dnsimple.com') do
-  its('stdout') { should match(Regexp.new(/208.93.64.253/)) }
+  its('stdout') { should match(Regexp.new(/104.245.210.170/)) }
 end
```

Maybe removing that test is best and instead use the `version.bind.` or other DNS info calls.

Attaching logs for other verify and converge fails for debugging

**Comment by mengesb** [comment]
[authoritative-multi-centos-69.log](https://github.com/dnsimple/chef-pdns/files/1773032/authoritative-multi-centos-69.log)
[authoritative-multi-centos-72.log](https://github.com/dnsimple/chef-pdns/files/1773033/authoritative-multi-centos-72.log)
[authoritative-multi-debian-88.log](https://github.com/dnsimple/chef-pdns/files/1773034/authoritative-multi-debian-88.log)
[authoritative-multi-ubuntu-1404.log](https://github.com/dnsimple/chef-pdns/files/1773035/authoritative-multi-ubuntu-1404.log)
[authoritative-multi-ubuntu-1604.log](https://github.com/dnsimple/chef-pdns/files/1773036/authoritative-multi-ubuntu-1604.log)
[authoritative-postgres-centos-72.log](https://github.com/dnsimple/chef-pdns/files/1773037/authoritative-postgres-centos-72.log)
[authoritative-postgres-debian-88.log](https://github.com/dnsimple/chef-pdns/files/1773038/authoritative-postgres-debian-88.log)
[authoritative-postgres-ubuntu-1404.log](https://github.com/dnsimple/chef-pdns/files/1773039/authoritative-postgres-ubuntu-1404.log)
[authoritative-postgres-ubuntu-1604.log](https://github.com/dnsimple/chef-pdns/files/1773040/authoritative-postgres-ubuntu-1604.log)
[kitchen.log](https://github.com/dnsimple/chef-pdns/files/1773041/kitchen.log)
[recursor-multi-centos-69.log](https://github.com/dnsimple/chef-pdns/files/1773042/recursor-multi-centos-69.log)
[recursor-multi-centos-72.log](https://github.com/dnsimple/chef-pdns/files/1773043/recursor-multi-centos-72.log)
[recursor-multi-debian-88.log](https://github.com/dnsimple/chef-pdns/files/1773044/recursor-multi-debian-88.log)
[recursor-multi-ubuntu-1404.log](https://github.com/dnsimple/chef-pdns/files/1773045/recursor-multi-ubuntu-1404.log)
[recursor-multi-ubuntu-1604.log](https://github.com/dnsimple/chef-pdns/files/1773046/recursor-multi-ubuntu-1604.log)

**Comment by mengesb** [comment]
mid-way I fixed the DNS DIG command above so I'm pretty sure everything would have failed to verify if it successfully converged

**Comment by onlyhavecans** [comment]
Are you submitting a PR for the test fixes?
I think to check that an IP is returned (\d+\.\d+\.\d+\.\d+) is likely far better than searching for a specific IP

**Comment by martinisoft** [comment]
I can submit a PR for fixing up some of the broken tests. It was a little short sighted to do this for the recursor tests since dnsimple.com's A record can change at any time.

**Comment by mengesb** [comment]
Thanks for the fix; I was not quite to PR status as I was enjoying a few 🍸 and 🍻 before working this one =) thanks for nailing it! :shipit:
